apiVersion: skaffold/v2beta27
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  platforms:
  - linux/amd64
  - linux/arm64/v8
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue-kubernetes
    # docker:
    #   target: jvm
    #   buildArgs:
    #     build: package
    custom:
      buildCommand: >-
        mvn
        package
        -Djib.allowInsecureRegistries=true
        -Dquarkus.container-image.push=true
      dependencies:
        paths:
        - "**/*"
        ignore:
        - target/**
# REVIEW test deploy is not updated for kkv-v2
# (and it's unclear how it would work now when we depend on kubernetes-client)
# deploy:
#   kustomize:
#     paths:
#     - ./test
profiles:
- name: prod-build
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value: >-
      mvn
      clean
      package
      -Pnative
      -Djib.allowInsecureRegistries=true
      -Dquarkus.container-image.push=true
